using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Acme.TestCaseManagement.Enums;
using Microsoft.OpenApi;
using Shouldly;
using Xunit;

namespace Acme.TestCaseManagement;

/// <summary>
/// T047: the OpenAPI document that the HttpApi module produces when it is hosted. The document is generated by the
/// sample host (ABP + Swashbuckle) and checked here as a contract: valid OpenAPI, the exact set of operations,
/// how each operation takes its input, and what the schemas promise.
/// </summary>
[Collection(HostCollection.Name)]
public class OpenApiContract_Tests
{
    private const string Root = "/api/test-case-management";

    private const string LoginPath = "/api/auth/login";

    private const string SchemaPrefix = "#/components/schemas/";

    /// <summary>
    /// The public HTTP surface as "operationId VERB route". Adding, removing or renaming an endpoint changes this
    /// list on purpose: it is a change of the contract that clients and generated proxies depend on.
    /// </summary>
    private static readonly string[] ExpectedOperations =
    {
        "TestSuite_GetTree GET /suites/tree",
        "TestSuite_Get GET /suites/{id}",
        "TestSuite_Create POST /suites",
        "TestSuite_Update PUT /suites/{id}",
        "TestSuite_Delete DELETE /suites/{id}",
        "TestSuite_Move POST /suites/{id}/move",

        "TestCase_GetList GET /test-cases",
        "TestCase_Get GET /test-cases/{id}",
        "TestCase_Create POST /test-cases",
        "TestCase_Update PUT /test-cases/{id}",
        "TestCase_Delete DELETE /test-cases/{id}",
        "TestCase_ReorderSteps PUT /test-cases/{id}/steps/order",
        "TestCase_SetTags PUT /test-cases/{id}/tags",
        "TestCase_GetTags GET /test-cases/tags",
        "TestCase_InsertSharedSteps POST /test-cases/{id}/shared-steps",
        "TestCase_RefreshSharedSteps POST /test-cases/{id}/shared-steps/{groupId}/refresh",
        "TestCase_DetachSharedSteps DELETE /test-cases/{id}/shared-steps/{groupId}",
        "TestCase_ChangeStatus POST /test-cases/{id}/status",
        "TestCase_GetVersions GET /test-cases/{id}/versions",
        "TestCase_GetVersion GET /test-cases/{id}/versions/{versionNumber}",
        "TestCase_GetDefectLinks GET /test-cases/{id}/defects",
        "TestCaseTransfer_Export GET /test-cases/export",
        "TestCaseTransfer_Import POST /test-cases/import",

        "TestPlan_GetList GET /plans",
        "TestPlan_Get GET /plans/{id}",
        "TestPlan_Create POST /plans",
        "TestPlan_Update PUT /plans/{id}",
        "TestPlan_Delete DELETE /plans/{id}",
        "TestPlan_ChangeStatus POST /plans/{id}/status",

        "TestRun_GetList GET /runs",
        "TestRun_Get GET /runs/{id}",
        "TestRun_Create POST /runs",
        "TestRun_AddItems POST /runs/{id}/items",
        "TestRun_AssignTester PUT /runs/{id}/items/{itemId}/assignee",
        "TestRun_ExecuteItem POST /runs/{id}/items/{itemId}/executions",
        "TestRun_GetExecutions GET /runs/{id}/items/{itemId}/executions",
        "TestRun_BatchExecute POST /runs/{id}/executions/batch",
        "TestRun_Complete POST /runs/{id}/complete",
        "TestRun_AddDefectLink POST /executions/{executionId}/defects",
        "TestRun_GetDefectLinks GET /executions/{executionId}/defects",
        "TestRun_UpdateDefectLink PUT /executions/{executionId}/defects/{defectLinkId}",
        "TestRun_RemoveDefectLink DELETE /executions/{executionId}/defects/{defectLinkId}",
        "TestResultTransfer_Export GET /runs/{runId}/results/export",
        "TestResultTransfer_Import POST /runs/{runId}/results/import",

        "Requirement_GetList GET /requirements",
        "Requirement_Get GET /requirements/{id}",
        "Requirement_Create POST /requirements",
        "Requirement_Update PUT /requirements/{id}",
        "Requirement_Delete DELETE /requirements/{id}",
        "Requirement_LinkTestCases POST /requirements/{id}/test-cases",
        "Requirement_UnlinkTestCase DELETE /requirements/{id}/test-cases/{testCaseId}",
        "Rtm_GetMatrix GET /rtm",

        "QualityGate_GetList GET /quality-gates",
        "QualityGate_Get GET /quality-gates/{id}",
        "QualityGate_Create POST /quality-gates",
        "QualityGate_Update PUT /quality-gates/{id}",
        "QualityGate_Delete DELETE /quality-gates/{id}",
        "QualityGate_Evaluate POST /quality-gates/evaluate",

        "SignOff_GetList GET /sign-off",
        "SignOff_Get GET /sign-off/{id}",
        "SignOff_SignOff POST /sign-off",
        "SignOff_Approve POST /sign-off/{id}/approvals",

        "ApiKey_GetList GET /api-keys",
        "ApiKey_Create POST /api-keys",
        "ApiKey_Revoke POST /api-keys/{id}/revoke",
        "AutomationResults_Publish POST /automation/results",

        "FlakyTest_GetList GET /flaky-tests",
        "FlakyTest_Apply POST /flaky-tests/apply",
        "Dashboard_Get GET /dashboard",

        "SharedStepGroup_GetList GET /shared-step-groups",
        "SharedStepGroup_Get GET /shared-step-groups/{id}",
        "SharedStepGroup_Create POST /shared-step-groups",
        "SharedStepGroup_Update PUT /shared-step-groups/{id}",
        "SharedStepGroup_Delete DELETE /shared-step-groups/{id}",
        "SharedStepGroup_GetUsage GET /shared-step-groups/{id}/usage",
        "SharedStepGroup_UpdateTestCases POST /shared-step-groups/{id}/update-test-cases",

        "Attachment_GetList GET /attachments",
        "Attachment_Upload POST /attachments",
        "Attachment_Download GET /attachments/{id}/content",
        "Attachment_Delete DELETE /attachments/{id}",

        // Outside the module: the host's own login endpoint, so that Swagger UI can obtain a token.
        "Auth_Login POST /api/auth/login",
    };

    private readonly TestCaseManagementHost _host;

    public OpenApiContract_Tests(TestCaseManagementHost host)
    {
        _host = host;
    }

    [Fact]
    public async Task The_Document_Is_Valid_OpenAPI_And_Every_Reference_Resolves()
    {
        var document = await GetDocumentAsync();

        var parsed = OpenApiDocument.Parse(document.ToJsonString(), "json");
        parsed.Document.ShouldNotBeNull();
        (parsed.Diagnostic?.Errors.Select(error => error.ToString()) ?? Enumerable.Empty<string>()).ShouldBeEmpty();

        ((string?)document["openapi"]).ShouldNotBeNull().ShouldStartWith("3.");
        ((string?)document["info"]?["title"]).ShouldBe(TestCaseManagementHttpApiHostModule.ApiTitle);

        var references = new List<string>();
        CollectReferences(document, references);
        references.ShouldNotBeEmpty();

        var schemas = Schemas(document);
        foreach (var reference in references.Distinct())
        {
            reference.ShouldStartWith(SchemaPrefix);
            schemas.ContainsKey(Uri.UnescapeDataString(reference[SchemaPrefix.Length..])).ShouldBeTrue($"{reference} does not resolve");
        }
    }

    [Fact]
    public async Task The_Document_Exposes_Exactly_The_Expected_Operations()
    {
        var document = await GetDocumentAsync();

        var actual = Operations(document).ToList();

        actual.ShouldAllBe(
            operation => operation.Path.StartsWith(Root + "/") || operation.Path == LoginPath,
            "only the module's routes and the login endpoint are documented");
        actual
            .Select(operation => $"{(string?)operation.Operation["operationId"]} {operation.Method} {(operation.Path.StartsWith(Root) ? operation.Path[Root.Length..] : operation.Path)}")
            .ShouldBe(ExpectedOperations, ignoreOrder: true);
    }

    [Fact]
    public async Task Every_Operation_Has_A_Unique_Id_Declares_Its_Inputs_And_Documents_Its_Errors()
    {
        var document = await GetDocumentAsync();
        var operations = Operations(document).ToList();

        operations.Select(operation => (string?)operation.Operation["operationId"]).ShouldBeUnique();

        foreach (var (method, path, operation) in operations)
        {
            var where = $"{method} {path}";
            var id = (string?)operation["operationId"];
            id.ShouldNotBeNullOrWhiteSpace(where);

            // Success and the shared error contract (RemoteServiceErrorResponse).
            var responses = operation["responses"]!.AsObject();
            responses.ContainsKey("200").ShouldBeTrue($"{where} has no 200 response");
            foreach (var status in new[] { "400", "401", "403", "404", "500" })
            {
                responses.ContainsKey(status).ShouldBeTrue($"{where} does not document {status}");
                responses[status]!.ToJsonString().ShouldContain("Volo.Abp.Http.RemoteServiceErrorResponse", Case.Sensitive, where);
            }

            // Every {token} of the route is a required path parameter, and nothing else is.
            var tokens = Regex.Matches(path, @"\{(\w+)\}").Select(match => match.Groups[1].Value).ToList();
            var parameters = (operation["parameters"] as JsonArray ?? new JsonArray()).Select(parameter => parameter!.AsObject()).ToList();
            var pathParameters = parameters.Where(parameter => (string?)parameter["in"] == "path").ToList();
            pathParameters.Select(parameter => (string)parameter["name"]!).ShouldBe(tokens, ignoreOrder: true, where);
            pathParameters.ShouldAllBe(parameter => (bool?)parameter["required"] == true, where);

            // POST and PUT take a JSON body (the commands without a payload excepted), the imports a multipart upload; GET and DELETE never do.
            var takesBody = operation["requestBody"] is not null;
            takesBody.ShouldBe(method is "POST" or "PUT" && id is not ("TestRun_Complete" or "ApiKey_Revoke"), $"{where}: request body");
            if (takesBody)
            {
                var bodyType = id is "TestCaseTransfer_Import" or "TestResultTransfer_Import" or "Attachment_Upload" ? "multipart/form-data" : "application/json";
                operation["requestBody"]!["content"]!.AsObject().ContainsKey(bodyType).ShouldBeTrue($"{where} body is not {bodyType}");
            }
        }
    }

    [Fact]
    public async Task Imports_Are_Uploads_And_Exports_Are_Downloads()
    {
        var document = await GetDocumentAsync();
        var operations = Operations(document).ToDictionary(operation => (string)operation.Operation["operationId"]!, operation => operation.Operation);

        foreach (var id in new[] { "TestCaseTransfer_Import", "TestResultTransfer_Import" })
        {
            var form = operations[id]["requestBody"]!["content"]!["multipart/form-data"]!["schema"]!;
            ((string?)form["properties"]!["File"]!["format"]).ShouldBe("binary", id);
            form["required"]!.AsArray().Select(name => (string)name!).ShouldBe(new[] { "File" }, id);
            ((string?)form["properties"]!["DryRun"]!["type"]).ShouldBe("boolean", id);
            operations[id]["responses"]!["200"]!.ToJsonString().ShouldContain("Transfer.Dtos.ImportReportDto", Case.Sensitive, id);
        }

        foreach (var id in new[] { "TestCaseTransfer_Export", "TestResultTransfer_Export" })
        {
            var content = operations[id]["responses"]!["200"]!["content"]!.AsObject();
            content.Select(media => media.Key).ShouldBe(
                new[] { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "text/csv" }, ignoreOrder: true, id);
            ((string?)content["text/csv"]!["schema"]!["format"]).ShouldBe("binary", id);
        }

        QueryParameters(document, "TestCaseTransfer_Export").ShouldBe(
            new[] { "Format", "Filter", "SuiteId", "IncludeDescendantSuites", "Status", "Priority", "Severity", "ExecutionType", "Kind", "Layer", "Tags", "HasAutomationId" },
            ignoreOrder: true);
        QueryParameters(document, "TestResultTransfer_Export").ShouldBe(new[] { "format" });
    }

    [Fact]
    public async Task The_Publish_Operation_Accepts_A_Token_Or_An_Api_Key_And_Describes_The_Key()
    {
        var document = await GetDocumentAsync();
        var operations = Operations(document).ToDictionary(operation => (string)operation.Operation["operationId"]!, operation => operation.Operation);

        var key = document["components"]!["securitySchemes"]!["ApiKey"]!;
        ((string?)key["type"]).ShouldBe("apiKey");
        ((string?)key["in"]).ShouldBe("header");
        ((string?)key["name"]).ShouldBe("X-Api-Key");

        // Alternatives: either one is enough.
        operations["AutomationResults_Publish"]["security"]!.AsArray()
            .Select(requirement => requirement!.AsObject().Single().Key)
            .ShouldBe(new[] { "Bearer", "ApiKey" });

        // Everything else asks for the token only: a key opens nothing but the publish endpoint.
        operations["TestCase_GetList"]["security"].ShouldBeNull();
        document["security"]!.AsArray().Select(requirement => requirement!.AsObject().Single().Key).ShouldBe(new[] { "Bearer" });

        var input = Property(Schemas(document), "Automation.Dtos.PublishAutomationResultsInput");
        ((bool)input("failOnUnmatched")["type"]!.ToJsonString().Contains("boolean")).ShouldBeTrue();
        ((int)input("results")["minItems"]!).ShouldBe(1);
        ((int)input("idempotencyKey")["maxLength"]!).ShouldBe(AutomationConsts.MaxIdempotencyKeyLength);
        Required(Schemas(document), "Automation.Dtos.AutomationResultInput").ShouldBe(new[] { "automationId" });
        Required(Schemas(document), "Automation.Dtos.CreateApiKeyDto").ShouldBe(new[] { "name" });
        Schemas(document).ContainsKey("Acme.TestCaseManagement.Automation.Dtos.ApiKeyDto").ShouldBeTrue();
        // Only the answer to creating a key has the secret.
        Property(Schemas(document), "Automation.Dtos.ApiKeyDto").ShouldNotBeNull();
        Schemas(document)["Acme.TestCaseManagement.Automation.Dtos.ApiKeyDto"]!["properties"]!.AsObject().ContainsKey("key").ShouldBeFalse();
        Schemas(document)["Acme.TestCaseManagement.Automation.Dtos.ApiKeyCreatedDto"]!.ToJsonString().ShouldContain("key");
    }

    [Fact]
    public async Task List_Endpoints_Take_Paging_And_Filters_As_Query_Parameters()
    {
        var document = await GetDocumentAsync();

        foreach (var id in new[] { "TestCase_GetList", "TestPlan_GetList", "TestRun_GetList", "Requirement_GetList", "SignOff_GetList" })
        {
            var query = QueryParameters(document, id);
            query.ShouldContain("SkipCount", id);
            query.ShouldContain("MaxResultCount", id);
            query.ShouldContain("Sorting", id);
        }

        QueryParameters(document, "TestCase_GetList").ShouldBe(
            new[]
            {
                "Filter", "SuiteId", "IncludeDescendantSuites", "Status", "Priority", "Severity", "ExecutionType", "Kind", "Layer", "Tags", "HasAutomationId",
                "Sorting", "SkipCount", "MaxResultCount",
            },
            ignoreOrder: true);

        QueryParameters(document, "Rtm_GetMatrix").ShouldBe(
            new[] { "MilestoneId", "Filter", "TestPlanId", "Environment", "Status", "SkipCount", "MaxResultCount" },
            ignoreOrder: true);

        QueryParameters(document, "TestRun_GetList").ShouldBe(
            new[] { "Filter", "TestPlanId", "Status", "Environment", "Sorting", "SkipCount", "MaxResultCount" },
            ignoreOrder: true);
    }

    [Fact]
    public async Task Schemas_Carry_The_Validation_Rules_Of_The_Dtos()
    {
        var schemas = Schemas(await GetDocumentAsync());

        var gate = Property(schemas, "QualityGates.Dtos.CreateUpdateQualityGateDto");
        Required(schemas, "QualityGates.Dtos.CreateUpdateQualityGateDto").ShouldBe(new[] { "name" });
        ((int)gate("name")["maxLength"]!).ShouldBe(QualityGateConsts.MaxNameLength);
        ((decimal)gate("minPassRate")["minimum"]!).ShouldBe(0.01m);
        ((decimal)gate("minPassRate")["maximum"]!).ShouldBe(100m);
        ((int)gate("requiredApprovals")["minimum"]!).ShouldBe(1);
        ((int)gate("requiredApprovals")["maximum"]!).ShouldBe(QualityGateConsts.MaxRequiredApprovals);

        Required(schemas, "Suites.Dtos.CreateTestSuiteDto").ShouldBe(new[] { "name" });
        ((int)Property(schemas, "Suites.Dtos.CreateTestSuiteDto")("name")["maxLength"]!).ShouldBe(TestSuiteConsts.MaxNameLength);

        Required(schemas, "TestCases.Dtos.CreateUpdateTestCaseDto").ShouldBe(new[] { "code", "title" }, ignoreOrder: true);
        Required(schemas, "TestCases.Dtos.TestStepDto").ShouldBe(new[] { "action", "expectedResult" }, ignoreOrder: true);
        Required(schemas, "Runs.Dtos.CreateTestRunDto").ShouldBe(new[] { "title", "environment" }, ignoreOrder: true);
        Required(schemas, "Runs.Dtos.BatchExecuteTestItemsDto").ShouldBe(new[] { "items" });
        ((int)Property(schemas, "Runs.Dtos.ExecuteTestItemDto")("durationSeconds")["minimum"]!).ShouldBe(0);
        ((int)Property(schemas, "Runs.Dtos.BatchExecuteTestItemsDto")("items")["minItems"]!).ShouldBe(1);
    }

    [Fact]
    public async Task Enums_Are_Integers_Whose_Names_Are_Documented()
    {
        var schemas = Schemas(await GetDocumentAsync());

        var documented = schemas.Where(schema => schema.Key.StartsWith("Acme.TestCaseManagement.Enums.")).ToList();
        documented.Count.ShouldBe(17);

        foreach (var (name, schema) in documented)
        {
            var enumType = typeof(PriorityLevel).Assembly.GetType(name);
            enumType.ShouldNotBeNull(name);

            ((string?)schema!["type"]).ShouldBe("integer", name);
            schema["enum"]!.AsArray().Select(value => (int)value!).ShouldBe(
                Enum.GetValues(enumType).Cast<object>().Select(Convert.ToInt32), name);
            schema["x-enum-varnames"]!.AsArray().Select(value => (string)value!).ShouldBe(Enum.GetNames(enumType), name);
        }
    }

    [Fact]
    public async Task Schema_Names_Are_Readable_And_Free_Of_Assembly_Qualified_Generics()
    {
        var schemas = Schemas(await GetDocumentAsync());

        foreach (var name in schemas.Select(schema => schema.Key))
        {
            name.ShouldNotContain("`", Case.Sensitive, name);
            name.ShouldNotContain("[", Case.Sensitive, name);
            name.ShouldNotContain(",", Case.Sensitive, name);
        }

        schemas.ContainsKey("Volo.Abp.Application.Dtos.PagedResultDtoOfTestCaseDto").ShouldBeTrue();
    }

    [Fact]
    public async Task Descriptions_Come_From_The_Application_Service_Interfaces_And_Dto_Members()
    {
        var document = await GetDocumentAsync();
        var operations = Operations(document).ToDictionary(operation => (string)operation.Operation["operationId"]!, operation => operation.Operation);

        ((string?)operations["TestSuite_GetTree"]["summary"]).ShouldBe("Returns the whole library as a forest of root suites, each with nested children.");
        ((string?)operations["TestCase_Create"]["summary"]).ShouldBe("Creates a Draft test case.");
        ((string?)operations["SignOff_SignOff"]["summary"]).ShouldNotBeNull().ShouldContain("quality gate is evaluated first");
        ((string?)operations["QualityGate_Evaluate"]["summary"]).ShouldNotBeNull().ShouldContain("without creating anything");

        var schemas = Schemas(document);
        ((string?)Property(schemas, "QualityGates.Dtos.CreateUpdateQualityGateDto")("minPassRate")["description"])
            .ShouldNotBeNull().ShouldContain("at most 100");
    }

    [Fact]
    public async Task Swagger_UI_Is_Served()
    {
        using var client = _host.CreateClient();

        using var response = await client.GetAsync("/swagger/index.html");

        response.IsSuccessStatusCode.ShouldBeTrue();
        response.Content.Headers.ContentType?.MediaType.ShouldBe("text/html");
    }

    private async Task<JsonObject> GetDocumentAsync()
    {
        using var client = _host.CreateClient();
        var json = await client.GetStringAsync("/swagger/v1/swagger.json");

        // Kept next to the test binaries so that a build server can publish the generated contract.
        await File.WriteAllTextAsync(Path.Combine(AppContext.BaseDirectory, "swagger.v1.json"), json);

        return JsonNode.Parse(json)!.AsObject();
    }

    private static IEnumerable<(string Method, string Path, JsonObject Operation)> Operations(JsonObject document)
    {
        foreach (var (path, item) in document["paths"]!.AsObject())
        {
            foreach (var (verb, operation) in item!.AsObject())
            {
                yield return (verb.ToUpperInvariant(), path, operation!.AsObject());
            }
        }
    }

    private static JsonObject Schemas(JsonObject document) => document["components"]!["schemas"]!.AsObject();

    private static List<string> QueryParameters(JsonObject document, string operationId)
    {
        var operation = Operations(document).Single(candidate => (string?)candidate.Operation["operationId"] == operationId).Operation;
        return (operation["parameters"] as JsonArray ?? new JsonArray())
            .Select(parameter => parameter!.AsObject())
            .Where(parameter => (string?)parameter["in"] == "query")
            .Select(parameter => (string)parameter["name"]!)
            .ToList();
    }

    /// <summary>Returns a lookup of the named property schemas of a module schema (name relative to the module namespace).</summary>
    private static Func<string, JsonNode> Property(JsonObject schemas, string schemaName)
    {
        var properties = schemas[$"Acme.TestCaseManagement.{schemaName}"]!["properties"]!.AsObject();
        return property => properties[property] ?? throw new InvalidOperationException($"{schemaName} has no property {property}");
    }

    private static List<string> Required(JsonObject schemas, string schemaName)
    {
        return (schemas[$"Acme.TestCaseManagement.{schemaName}"]!["required"] as JsonArray ?? new JsonArray())
            .Select(name => (string)name!)
            .ToList();
    }

    private static void CollectReferences(JsonNode? node, List<string> references)
    {
        switch (node)
        {
            case JsonObject obj:
                foreach (var (key, value) in obj)
                {
                    if (key == "$ref" && value is JsonValue reference && reference.TryGetValue<string>(out var target))
                    {
                        references.Add(target);
                    }
                    else
                    {
                        CollectReferences(value, references);
                    }
                }

                break;

            case JsonArray array:
                foreach (var item in array)
                {
                    CollectReferences(item, references);
                }

                break;
        }
    }
}
